### ISSUE TITLE
Update the new documentation home 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal/documentation#10]
## Context

After merging https://github.com/ontoportal/administration/pull/4 pull request, now we have a new home page see https://ontoportal.github.io/administration/ 

I will let the management and documentation teams decide what would be it role and its content, but at least i think we need to set the new (future) documentation structure and redirect for the administration for now.

## How to 

See https://github.com/ontoportal/administration/issues/11#issuecomment-1352809501

**Comment by jonquet** [comment]
@graybeal Have tou status on the renaming of the repository from "administration" to "documentation" 
I can do it if you're ok.. but it will break a couple of links... although GitHub handles the redirects, its worth knowing.

**Comment by graybeal** [comment]
A few links are already broken (haven't had a moment to report that), so I'd say let's move forward and then see what we have to clean up. If you're able to make that happen I'd totally vote in favor.
