### ISSUE TITLE
Redirect https://ontoportal.org/documentation to  https://ontoportal.github.io/documentation/

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal/documentation#36]
Hi @alexskr , do you think you can add a rerouting of https://ontoportal.org/documentation to  https://ontoportal.github.io/documentation

It will be easier like this to go to the documentation and unify the domain name.

**Comment by alexskr** [comment]
done via https://github.com/ontoportal/website/commit/beebe5ea468caf19a60e8481288779ed15559c2b
