### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by galviset** [ontoportal/documentation#42]
With an upcoming support of several languages in the interface of portals brought by AgroPortal, it naturally brings the question of doing it for the documentation as well.
It might not be as relevant for developers/maintainers than it is for users, but this idea is more concerning a future user documentation.

**Comment by jonquet** [comment]
Relevant discussion about Documentation is there. https://github.com/ontoportal/ontoportal-project/discussions/1
I have reported your comment there. I believe we first need a documentaiton (User guide) before we translate it ;)
